### ISSUE TITLE
Enable Script Visuals

### ISSUE THREAD

**Issue by davidoconnortw** [alefranzoni/power-refresher#2]
Is it possible to add a feature to automatically click "Enable" when the Enable Script Visuals dialog box pops up? This happens automatically when you open a .pbix file with Python visuals, etc.

<img width="361" alt="enable-script-visuals" src="https://user-images.githubusercontent.com/85643454/200644993-014827cd-8dd2-4094-a282-d6916f307c53.png">

**Comment by alefranzoni** [comment]
Yes, no problem. I guess that it shouldn't take much time for me to add it. Could you give me a dummy pbix file with some script visual inside to check the behavior? Thanks.

**Comment by davidoconnortw** [comment]
Here's a sample presentation. Thanks for your help!

[sample presentation.zip](https://github.com/alefranzoni/power-refresher/files/9983355/sample.presentation.zip)

**Comment by davidoconnortw** [comment]
Hi Ale, this is working perfectly now for .pbix files that have Python Visuals. Thanks again. 

For whatever reason, though: for Power BI files without Python Visuals it's not working, even after setting 
"-enable_script_visuals=False". I had to add Python visuals to those presentations and then hide them to get your script to work. Not a big deal, just letting you know.

Btw, if you ever get a Paypal or something like that I'll send you a few bucks.

**Comment by alefranzoni** [comment]
Oops, you're right. I totally forgot to add a few lines of code. Within the upcoming release, this will be fixed. Plus, I'll add an option to continue with the refresh process even if the script visuals were disabled by user choice, instead to break the execution. The new version should be ready for tomorrow, stay tuned 🙌🏻.

About PayPal, yes, I edited the README file and added a donate section, so you can find the link there. Thank you so much for your support, really, I appreciate it so much.
